### ISSUE TITLE
Need to move Test namespace to dev

### ISSUE THREAD

**Issue by geggleto** [originphp/originphp#45]
You should have 2 autoloads; you should move the Test namespace to `autoload-dev`

**Comment by jamielsharief** [comment]
Agreed

**Comment by jamielsharief** [comment]
Originally the project was designed to work with the Docker Environment, so that when the projects are uploaded to the staging and production, you know it works. However since I have added the built in server, and making it more flexible its creating a bit of confusion. Since if a user wants to use the DDE then composer is going to install all this extra stuff.

What is your opinion re this and what I have said? note. i have added required dev. 

{
  "name": "originphp/framework",
  "description": "The OriginPHP framework",
  "type": "library",
  "keywords": [
    "originPHP",
    "framework",
    "mvc",
    "easy",
    "simple",
    "convention over configuration",
    "orm",
    "docker",
    "rapid"
  ],
  "homepage": "https://www.originphp.com",
  "license": "MIT",
  "authors": [
    {
      "name": "Jamiel Sharief",
      "email": "js@originphp.com"
    }
  ],
  "autoload": {
    "psr-4": {
      "Origin\\": "src/"
    }
  },
  "autoload-dev": {
    "psr-4": {
      "Origin\\Test\\": "tests/"
    }
  },
  "require": {
    "php": "^7.2.0",
    "ext-json": "*",
    "ext-mbstring": "*",
    "ext-openssl": "*",
    "ext-intl": "*"
  },
  "require-dev": {
    "phpunit/phpunit": "7.5.2",
    "phpseclib/phpseclib": "*",
    "ext-curl": "*",
    "ext-memcached": "*"
  }
}
